services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
  redis:
    image: redis/redis-stack-server
    ports:
      - '6379:6379'

  qdrant:
    image: qdrant/qdrant
    ports:
      - '6333:6333'
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
